### ISSUE TITLE
Missing config.yml file

### ISSUE THREAD

**Issue by mathieu-b** [mattaylor/emoosc#1]
I have followed the instructions in the ```README.md``` file.

I'm using Windows 10 and have installed the latest LTS version of Node.js.

Actually the ```emoosc``` folder is created inside a folder called ```node_modules```.

When I enter that ```emoosc``` folder and run ```npm run -- config.yml```, it fails since no ```config.yml``` is to be found anywhere.

Any clues?

Regards

**Comment by mattaylor** [comment]
config.js should be used instead of config.yml. I have updated the readme
